---
# Ansible playbook to set up or update my home directory and related stuff.

- hosts: all
  tasks:

    - name: Create ~/.ssh
      ansible.builtin.file:
        state: directory
        mode: '0700'
        path: '{{ ansible_facts.env.HOME }}/.ssh'

    - name: Create other directories
      ansible.builtin.file:
        state: directory
        recurse: yes
        path: '{{ ansible_facts.env.HOME }}/{{ item }}'
      loop:
        - .config/git
        - .emacs.d
        - .vim
        - git

    - name: Clone or update dotfiles repo
      ansible.builtin.git:
        repo: https://gitlab.com/kenyon/dotfiles.git
        dest: '{{ ansible_facts.env.HOME }}/git/dotfiles'
        update: yes

    - name: Create symlinks to dotfiles
      ansible.builtin.file:
        state: link
        force: yes
        path: '{{ ansible_facts.env.HOME }}/{{ item }}'
        src: '{{ ansible_facts.env.HOME }}/git/dotfiles/{{ item }}'
      loop:
        - .Xresources
        - .aspell.en.prepl
        - .aspell.en.pws
        - .bash_aliases
        - .bash_profile
        - .bashrc
        - .bashrc.local
        - .config/git/ignore
        - .devscripts
        - .dput.cf
        - .emacs.d
        - .gitconfig
        - .inputrc
        - .profile
        - .quiltrc
        - .screenrc
        - .signature
        - .tmux.conf
        - .toprc
        - .vim
        - .vimrc
        - .zlogin
        - .zshenv
        - .zshrc

...
