#!/bin/zsh

# Update environment variables in a tmux session from the variables
# outside. Specifically useful to update SSH_AUTH_SOCK after attaching
# to a tmux session.

function fixssh ()
{
    eval $(tmux show-environment -s)
}
